### ISSUE TITLE
Remote Plugin injection with executions

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#258]
Currently executions are ignored; we should consider injecting them as well

**Comment by rnc** [comment]
If, in the remote executions the id already exists in the local an exception will be thrown.

**Comment by rnc** [comment]
Should be fixed now

**Comment by pgier** [comment]
After the fix, PME is now injecting all plugins in pluginManagement, even the ones which don't have any configuration.  I'm not sure if this is the desired behavior, I somewhat prefer the old behavior.

Also, when we had previously discussed injecting plugin executions, I was referring to the executions that are in the build/plugins section of the POM, and not the ones in the pluginManagement section.  Executions in the pluginManagement section aren't normally that useful since they aren't executed.
