### ISSUE TITLE
Inject plugin configuration from the main plugins section of the POM

### ISSUE THREAD

**Issue by pgier** [release-engineering/pom-manipulation-ext#270]
Also see related #91 and #258
PME currently allows plugin configuration in the plugin management section to be injected into a POM, however it is not possible to inject plugin definitions from the main <build><plugins> section.  This would be useful if for example you wanted to inject the buildnumber maven plugin execution from the jboss-parent for example.  In the jboss-parent, this plugin is set to run for every build in order to get the scm revision into a property which can be stored in metadata files.
The recent change in #258 allows plugin executions from the <pluginManagement> to be injected into the build, however this is somewhat useless since these executions are not actually run during the build.  Only executions defined in the main <build><plugins> section of the POM are actually run during the build.

**Comment by pgier** [comment]
Just wanted to note that this can currently be accomplished using a profile which is on by default, so this feature isn't absolutely necessary since there is a relatively easy workaround.  It might even be better to not implement this just to ensure that any config injected into the main plugin section is isolated into a profile.

**Comment by jdcasey** [comment]
I guess with all the complexity of merging deep xml trees (for plugin configuration), I'd prefer to see this done via profiles. You can set your profile to activate when a property is not false, which is like using activeByDefault...but it's non-exclusive (so you could have five profiles doing this, instead of just one).

Injecting via profile also makes it easy to see how we've annotated the POM file, which IMO is a nice piece of implicit documentation.

**Comment by pgier** [comment]
Yes, I agree, let's leave the current behavior as-is and require the use of a profile for injecting plugins.  If we find a compelling use case in the future, we can always revisit this.

**Comment by pgier** [comment]
Closing this issue since we agreed that for now it's better to keep the current behavior.
